export type Song = {
  songId: string;
  isrc: string;
  title: string;
  artist: string;
  parentalAdvisory: string;
  adultOnly: boolean;
  label: string;
  subLabel: string;
  displayedTitle: string;
  displayedArtist: string;
  artwork: string;
  itunes: string;
  spotify?: string | null;
  sample_aac10: string;
  sample_wav10: string;
  sample_mp310: string;
  sample_ogg10: string;
  sample_aac20: string;
  sample_wav20: string;
  sample_mp320: string;
  sample_mp320_enc: string;
  sample_ogg20: string;
  sample_ogg20_enc: string;
  sample_aac30: string;
  sample_wav30: string;
  sample_mp330: string;
  sample_ogg30: string;
  playlistId?: string;
};
